package com.stevengantz.json;

/**
 * Jackson element generated by http://www.jsonschema2pojo.org/
 * Created by Steven Gantz on 2/26/2017.
 *
 */
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.commons.lang.builder.ToStringBuilder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({ "buttontext", "linkURL" })
public class Button {

	@JsonProperty("buttontext")
	private String buttontext;
	@JsonProperty("linkURL")
	private String linkURL;
	@JsonIgnore
	private Map<String, Object> additionalProperties = new HashMap<>();

	@JsonProperty("buttontext")
	public String getButtontext() {
		return buttontext;
	}

	@JsonProperty("buttontext")
	public void setButtontext(String buttontext) {
		this.buttontext = buttontext;
	}

	public Button withButtontext(String buttontext) {
		this.buttontext = buttontext;
		return this;
	}

	@JsonProperty("linkURL")
	public String getLinkURL() {
		return linkURL;
	}

	@JsonProperty("linkURL")
	public void setLinkURL(String linkURL) {
		this.linkURL = linkURL;
	}

	public Button withLinkURL(String linkURL) {
		this.linkURL = linkURL;
		return this;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	@JsonAnyGetter
	public Map<String, Object> getAdditionalProperties() {
		return this.additionalProperties;
	}

	@JsonAnySetter
	public void setAdditionalProperty(String name, Object value) {
		this.additionalProperties.put(name, value);
	}

	public Button withAdditionalProperty(String name, Object value) {
		this.additionalProperties.put(name, value);
		return this;
	}

}
