package com.stevengantz.json;

/**
 * Jackson element generated by http://www.jsonschema2pojo.org/
 * Created by Steven Gantz on 2/26/2017.
 *
 */
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import org.apache.commons.lang.builder.ToStringBuilder;

@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({ "DirectoryTitle", "DirectoryHexColor", "PageBackgroundURL", "cards" })
public class Config {

	@JsonProperty("DirectoryTitle")
	private String directoryTitle;
	@JsonProperty("DirectoryHexColor")
	private String directoryHexColor;
	@JsonProperty("PageBackgroundURL")
	private String pageBackgroundURL;
	@JsonProperty("cards")
	private List<Card> cards = null;
	@JsonIgnore
	private Map<String, Object> additionalProperties = new HashMap<String, Object>();

	@JsonProperty("DirectoryTitle")
	public String getDirectoryTitle() {
		return directoryTitle;
	}

	@JsonProperty("DirectoryTitle")
	public void setDirectoryTitle(String directoryTitle) {
		this.directoryTitle = directoryTitle;
	}

	public Config withDirectoryTitle(String directoryTitle) {
		this.directoryTitle = directoryTitle;
		return this;
	}

	@JsonProperty("DirectoryHexColor")
	public String getDirectoryHexColor() {
		return directoryHexColor;
	}

	@JsonProperty("DirectoryHexColor")
	public void setDirectoryHexColor(String directoryHexColor) {
		this.directoryHexColor = directoryHexColor;
	}

	public Config withDirectoryHexColor(String directoryHexColor) {
		this.directoryHexColor = directoryHexColor;
		return this;
	}

	@JsonProperty("PageBackgroundURL")
	public String getPageBackgroundURL() {
		return pageBackgroundURL;
	}

	@JsonProperty("PageBackgroundURL")
	public void setPageBackgroundURL(String pageBackgroundURL) {
		this.pageBackgroundURL = pageBackgroundURL;
	}

	public Config withPageBackgroundURL(String pageBackgroundURL) {
		this.pageBackgroundURL = pageBackgroundURL;
		return this;
	}

	@JsonProperty("cards")
	public List<Card> getCards() {
		return cards;
	}

	@JsonProperty("cards")
	public void setCards(List<Card> cards) {
		this.cards = cards;
	}

	public Config withCards(List<Card> cards) {
		this.cards = cards;
		return this;
	}

	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this);
	}

	@JsonAnyGetter
	public Map<String, Object> getAdditionalProperties() {
		return this.additionalProperties;
	}

	@JsonAnySetter
	public void setAdditionalProperty(String name, Object value) {
		this.additionalProperties.put(name, value);
	}

	public Config withAdditionalProperty(String name, Object value) {
		this.additionalProperties.put(name, value);
		return this;
	}

}
